import Head from "next/head"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mb Psicologia - Technical Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://mbpsicologia.com.br/wp-content/uploads/2022/02/cropped-MBLO-32x32.png" sizes="32x32" />
      </Head>
      <main className={`${inter.className}`}>
        <h1 style={{color: 'var(--green)'}}>boilerplate</h1>
      </main>
    </>
  )
}
